import "./home.scss"

function Home() {
  return (
    <div>Home
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    </div>
  )
}

export default Home